import { Prompt } from './types'

export const defaultPrompts: Prompt[] = [
  {
    id: 'coding-react-component',
    title: 'React Component Builder',
    icon: 'Terminal',
    category: 'coding',
    tags: ['react', 'component', 'typescript'],
    variables: ['componentName', 'props'],
    role: 'You are a senior React developer and TypeScript expert specializing in modern React patterns and component architecture.',
    content: 'Create a React component called {componentName} with the following props: {props}. Use TypeScript, functional components, and modern React patterns. Include proper typing and error handling.',
    version: 1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'coding-api-endpoint',
    title: 'API Endpoint Design',
    icon: 'Terminal',
    category: 'coding',
    tags: ['api', 'backend', 'rest'],
    variables: ['endpoint', 'method', 'purpose'],
    role: 'You are a backend architect with expertise in RESTful API design, security best practices, and scalable system architecture.',
    content: 'Design a {method} API endpoint for {endpoint} that {purpose}. Include request/response schemas, error handling, validation, and security considerations.',
    version: 1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'coding-algorithm',
    title: 'Algorithm Implementation',
    icon: 'Terminal',
    category: 'coding',
    tags: ['algorithm', 'performance', 'optimization'],
    variables: ['algorithm', 'constraints'],
    role: 'You are a computer science expert specializing in algorithms, data structures, and computational complexity analysis.',
    content: 'Implement {algorithm} with the following constraints: {constraints}. Optimize for time and space complexity. Include complexity analysis and test cases.',
    version: 1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'image-portrait',
    title: 'Professional Portrait',
    icon: 'Image',
    category: 'image',
    tags: ['portrait', 'photography', 'professional'],
    variables: ['subject', 'style'],
    role: 'You are a professional portrait photographer with expertise in studio lighting, composition, and creating flattering images that capture personality and emotion.',
    content: 'Create a professional portrait of {subject} in {style} style. Studio lighting setup with key, fill, and rim lights. Shallow depth of field, f/2.8. Clean background. Professional color grading.',
    version: 1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'image-product',
    title: 'Product Photography',
    icon: 'Image',
    category: 'image',
    tags: ['product', 'commercial', 'photography'],
    variables: ['product', 'background'],
    role: 'You are a commercial product photographer specializing in catalog photography, e-commerce imagery, and creating compelling product visuals that drive sales.',
    content: '{product} on {background} background. Professional product photography. Studio lighting with soft shadows. Sharp focus throughout. Commercial quality. High resolution.',
    version: 1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'image-landscape',
    title: 'Cinematic Landscape',
    icon: 'Image',
    category: 'image',
    tags: ['landscape', 'nature', 'cinematic'],
    variables: ['location', 'time'],
    role: 'You are a landscape photographer known for capturing epic vistas, dramatic natural light, and awe-inspiring scenes from around the world.',
    content: 'Cinematic landscape photograph of {location} at {time}. Epic composition with dramatic sky. Golden hour lighting. Wide angle lens. Depth and atmosphere. Nature photography at its finest.',
    version: 1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'video-commercial',
    title: 'Commercial Video',
    icon: 'Video',
    category: 'video',
    tags: ['commercial', 'advertising', 'video'],
    variables: ['product', 'duration', 'mood'],
    role: 'You are a commercial video director with experience creating engaging advertisements, brand films, and promotional content for major brands.',
    content: 'Create a {duration} second commercial video for {product} with {mood} mood. Include dynamic camera movements, professional color grading, and compelling visual storytelling. Cinema camera quality.',
    version: 1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'video-tutorial',
    title: 'Tutorial Video',
    icon: 'Video',
    category: 'video',
    tags: ['tutorial', 'educational', 'video'],
    variables: ['topic', 'level'],
    role: 'You are an educational video producer specializing in creating clear, engaging tutorials that break down complex topics into easy-to-follow steps.',
    content: 'Create a tutorial video about {topic} for {level} level. Clear demonstrations, smooth transitions, professional voiceover quality. Step-by-step visual progression.',
    version: 1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'research-literature-review',
    title: 'Literature Review',
    icon: 'MagnifyingGlass',
    category: 'research',
    tags: ['research', 'academic', 'literature'],
    variables: ['topic', 'timeframe'],
    role: 'You are an academic researcher with expertise in conducting systematic literature reviews, synthesizing research findings, and identifying gaps in scholarly work.',
    content: 'Conduct a comprehensive literature review on {topic} covering research from {timeframe}. Identify key themes, methodologies, findings, and gaps in current research. Synthesize insights and suggest future research directions.',
    version: 1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'research-data-analysis',
    title: 'Data Analysis Plan',
    icon: 'MagnifyingGlass',
    category: 'research',
    tags: ['research', 'data', 'analysis'],
    variables: ['dataset', 'objective'],
    role: 'You are a data scientist with expertise in statistical analysis, data visualization, and deriving actionable insights from complex datasets.',
    content: 'Create a data analysis plan for {dataset} with the objective of {objective}. Include data cleaning strategies, statistical methods, visualization approaches, and validation techniques.',
    version: 1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'planning-project',
    title: 'Project Plan',
    icon: 'ListChecks',
    category: 'planning',
    tags: ['planning', 'project', 'management'],
    variables: ['project', 'timeline', 'team'],
    role: 'You are a project manager with extensive experience in planning, coordinating resources, managing risks, and delivering successful projects on time and within budget.',
    content: 'Create a comprehensive project plan for {project} with {timeline} timeline and {team} team size. Include milestones, deliverables, resource allocation, risk assessment, and success metrics.',
    version: 1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'planning-sprint',
    title: 'Sprint Planning',
    icon: 'ListChecks',
    category: 'planning',
    tags: ['planning', 'agile', 'sprint'],
    variables: ['sprintGoal', 'duration'],
    role: 'You are an agile coach and scrum master with deep experience in sprint planning, user story creation, and facilitating productive development cycles.',
    content: 'Plan a {duration} sprint focused on {sprintGoal}. Break down into user stories, estimate story points, identify dependencies, and create acceptance criteria for each task.',
    version: 1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'agents-customer-support',
    title: 'Customer Support Agent',
    icon: 'Robot',
    category: 'agents',
    tags: ['agent', 'support', 'automation'],
    variables: ['product', 'tone'],
    role: 'You are a customer success expert specializing in designing AI-powered support systems that provide helpful, empathetic assistance while maintaining brand voice.',
    content: 'Design a customer support agent for {product} with {tone} communication style. Define handling common questions, escalation protocols, knowledge base integration, and customer satisfaction metrics.',
    version: 1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'agents-code-reviewer',
    title: 'Code Review Agent',
    icon: 'Robot',
    category: 'agents',
    tags: ['agent', 'code', 'review'],
    variables: ['language', 'standards'],
    role: 'You are a senior software engineer and code quality expert who reviews code for best practices, security vulnerabilities, performance issues, and maintainability.',
    content: 'Create a code review agent for {language} following {standards} coding standards. Check for bugs, security issues, performance problems, and style consistency. Provide constructive feedback.',
    version: 1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'agents-content-moderator',
    title: 'Content Moderation Agent',
    icon: 'Robot',
    category: 'agents',
    tags: ['agent', 'moderation', 'safety'],
    variables: ['platform', 'rules'],
    role: 'You are a content moderation specialist focused on creating safe online communities through consistent policy enforcement and thoughtful escalation processes.',
    content: 'Design a content moderation agent for {platform} enforcing {rules}. Define content review criteria, flagging mechanisms, human escalation triggers, and reporting systems.',
    version: 1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
]
